sudo: false
language: node_js
node_js:
  - "4"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - 'npm i'
script: "npm run lint"
script: "npm build && node_modules/karma/bin/karma start karma.conf.js --single-run"
